use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :werewolf_api, WerewolfApiWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :werewolf_api, WerewolfApi.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "werewolf_api_dev",
  hostname: "localhost",
  pool_size: 10

config :werewolf_api, WerewolfApi.Guardian,
  issuer: "werewolf_api",
  secret_key: "3LFz3icTUpreLyrxI4SNdHhTU5R5STMKSpzCHTnYCVf+uAHPRO+TodZHXJ3W0i/e"

config :pigeon, :fcm,
  fcm_default: %{
    key:
      "AAAAiRI7y9A:APA91bEul9-hpglDfso3LnR1BG7dJfzxS0t2KB2Srl0WQpQtdp0kqKuBlsXfVzjN1nX0Mfhkbli88M9Glq6vHYxt_mICmD8kilqXxs3HQQYew26e86fk0gFm0bj4mP-v--mBJfakjkY1"
  }

config :werewolf_api, :dynamic_links,
  firebase_api: System.get_env("FIREBASE_API"),
  bundle_id: System.get_env("BUNDLE_ID"),
  app_store_id: System.get_env("APP_STORE_ID")

config :werewolf_api, :apple_auth,
  client_id: System.get_env("BUNDLE_ID"),
  team_id: System.get_env("APPLE_TEAM_ID"),
  private_key_id: System.get_env("APPLE_PRIVATE_KEY_ID"),
  private_key: System.get_env("APPLE_PRIVATE_KEY")
