defmodule WerewolfApi.Conversation.Message do
  use Ecto.Schema
  import Ecto.Changeset

  schema "messages" do
    field(:body, :string)
    field(:bot, :boolean, default: false)
    field(:type, :string)
    # read_after_writes for the uuid, as generated by DB
    field(:uuid, :binary_id, read_after_writes: true)
    field(:quote_uuid, :string)
    belongs_to(:user, WerewolfApi.User)
    belongs_to(:conversation, WerewolfApi.Conversation)

    timestamps()
  end

  @doc false
  def changeset(message, attrs) do
    message
    |> cast(attrs, [:body, :bot, :type, :uuid, :quote_uuid])
    |> validate_required([:body])
  end

  def username(%{bot: true} = message) do
    "Narrator"
  end

  def username(message) do
    WerewolfApi.User.display_name(message.user)
  end
end
